### ISSUE TITLE
include links does not work with direct url

### ISSUE THREAD

**Issue by nbabenko** [threefoldfoundation/lapis-wiki#11]
https://www2.foundation.grid.tf/#/definitions/threefold_cloud_units
When we put direct URL in include macros wiki does not work properly:

Source:
`!!!include("https://github.com/threefoldfoundation/info_grid/blob/master/docs/concepts/cloud_units.md")

!!!include("https://raw.githubusercontent.com/threefoldfoundation/info_grid/master/docs/concepts/cloud_units.md")
`

Wiki result:
`ERROR IN MACRO*** TODO: *1 ***
macro:
include
ERROR:
ERROR: Cannot find doc with name:docs.concepts.cloud_units (nr docs found:0)
ERROR IN MACRO*** TODO: *1 ***
macro:
include
ERROR:
not a valid github url`

**Comment by VonSub** [comment]
!!!include("https://github.com/freeflownation/info_freeflownation/blob/master/docs/freeflownation_why/efficiency-resillience.md")

works here:

https://www2.info.threefold.tech/#/blogs/decentralized-system-does-not-exist-yet

**Comment by abom** [comment]
The second links is not valid, we don't use the `raw` link, instead it should be like:
`https://github.com/threefoldfoundation/info_grid/blob/master/docs/concepts/cloud_units.md`

**Comment by abom** [comment]
It seems like there're two problems now with includes:
1. Including a link from external websites (docsites) sometimes doesn't work properly.
2. Including a document with links (to local images for example) won't update this links and hence they won't be found (different path).

A solution to (2) is by downloading/copying the images to the local directory of the document where include macro is used.

Trying to figure out what's the problem with (1), then will implement the solution of (2).

**Comment by abom** [comment]
Fixed the main problem stated in this issue, obsolete `docs_config.toml` was used/referenced, the fix can be found at https://github.com/threefoldtech/jumpscaleX/commit/f9d23c98eff50d896bd98a82533462aab7077852.

**Comment by abom** [comment]
@rkhamis we need some labels for this project :)

**Comment by zaibon** [comment]
@abom I've added the labels

**Comment by abom** [comment]
Still working on the second point, trying to resolve the paths problem by copying any link to the current document path where include is used.

Links might be in the form of:
- URL (this will be as is without copying)
- Absolute paths (root is the included document root).
- Relative paths to included document.

Trying to expand these paths in a proper way.

**Comment by abom** [comment]
(2) is done https://github.com/threefoldtech/jumpscaleX/commit/627425243bf90c6a9f8580564ca7eaf91dec8167.

**Comment by abom** [comment]
@nbabenko please update the links not to use the raw github link (as stated in https://github.com/threefoldtech/OpenPublish/issues/11#issuecomment-488243910).
