### ISSUE TITLE
Filtering on projects and contributions combined, while respecting the order/position.

### ISSUE THREAD

**Issue by VonSub** [threefoldfoundation/lapis-wiki#15]
We need to be able to filter to combinations of projects and contribution levels so we can feature teams specific per contribution level on each project.

**Comment by abom** [comment]
- [x] Also we need to set the right path of images.

**Comment by abom** [comment]
Done at https://github.com/threefoldtech/jumpscaleX/commit/12271369ffd35e31440d82ef95ea46ec14ed7baa, jumpscale need to be updated on production.
