### ISSUE TITLE
scroll at wikis mobile 

### ISSUE THREAD

**Issue by ehab-hassan** [threefoldfoundation/lapis-wiki#18]
scroll at wikis mobile not working 
ex:
https://info.incubaid.com/#/webcontent/exits/amplidata

**Comment by abom** [comment]
Trying to look for media specific styles (specially with `overflow: hidden` or `z-index`).

**Comment by abom** [comment]
@samaradel Do you have any input here, what might cause this problem? (see https://github.com/threefoldtech/OpenPublish/issues/18#issuecomment-491609731).

**Comment by ehab-hassan** [comment]
Fixed
