### ISSUE TITLE
docsite.js has problems with page loading

### ISSUE THREAD

**Issue by samaradel** [threefoldfoundation/lapis-wiki#19]
Sometimes, the page loads the content without latest updates to the DOM from other e.g. jquery plugins.

**Comment by abom** [comment]
Should be fixed by https://github.com/threefoldtech/jumpscale_weblibs/commit/d0617bab1c8f69ccdce99647da75828f8d7a9418

Currently, the updates are done element by element, instead of the whole content (hope it works well!).
