### ISSUE TITLE
team widget/macro for websites

### ISSUE THREAD

**Issue by samaradel** [threefoldfoundation/lapis-wiki#20]
We have a docisify plugin for team widget, but it's not usable in websites, we need a way to use it the same way in websites.

Team js library: https://github.com/threefoldtech/jumpscale_weblibs/tree/master/static/team
Team macro: https://github.com/threefoldtech/digitalmeX/blob/development/docs/publishing_platform/wiki/macro/team.md

**Comment by abom** [comment]
Done, related commits are https://github.com/threefoldtech/jumpscale_weblibs/commit/5445e9bf131651f908b3347e5b69843ad09b11f2 and https://github.com/threefoldtech/jumpscale_weblibs/commit/ba3536b39186ec9dc7d61885d6627b308bd0ea69.

Now you can use [team.js](https://github.com/threefoldtech/jumpscale_weblibs/tree/master/static/team) in any website, just put the json object inside a `<code>` tag inside an e.g. div with a class `team-container` and execute the following code with page load.

```javascript
TeamWidget.avatarPrefix = '/path/to/docsite/; //  e.g. /docsites/threefold
TeamWidget.init();
```

If used with `docsite.js`, it must be executed after the docsite is loaded:

```javascript
var docsite = new DocSite()
docsite.docsiteLoaded = function() {
    TeamWidget.avatarPrefix = '/path/to/docsite/; //  e.g. /docsites/threefold
    TeamWidget.init();
};
docsite.init();
```

For using it with [markdown macros](https://github.com/threefoldtech/digitalmeX/tree/development/docs/publishing_platform/wiki/macro), you can create a new file called e.g. `team.md` with the right content like

````md
+++
+++

```
!!!team
link = "https://github.com/threefoldfoundation/data_team/tree/master/team"
order = "rank"
project_ids = [1]
```
````

And inside html something like:

```html
<div class="team-container">
     {{{ threefold.[team].content }}}
</div>
```

And when calling TeamWidget.init(), it will replace the data of this div by the team widget.
