### ISSUE TITLE
openpublish server crashes when pulling repositories  (auto-deployment fails)

### ISSUE THREAD

**Issue by PeterNashaat** [threefoldfoundation/lapis-wiki#22]
issue in the auto-deployment 
![autod3](https://user-images.githubusercontent.com/13523434/58251780-c792d080-7d64-11e9-81ac-ec179b12690e.jpg)
![autod2](https://user-images.githubusercontent.com/13523434/58251782-c82b6700-7d64-11e9-9059-24703e0b74b0.jpg)
![autod1](https://user-images.githubusercontent.com/13523434/58251784-c82b6700-7d64-11e9-9501-244e44d69235.jpg)

**Comment by abom** [comment]
Also

```
Sun 16 10:55:44 GitFactory.py    - 346 - j.clients.git:gitfactory           : git pull ssh://git@github.com/threefoldfoundation/info_tokens.git -> /sandbox/code/github/threefoldfoundation/info_tokens

ssh: connect to host github.com port 22: Connection timed out
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

could not push/pull ssh://git@github.com/threefoldfoundation/info_tokens.git
```

Do not know where is the problem and if it's github, doing `ssh -T git@ssh.github.com` didn't timeout.

**Comment by abom** [comment]
Pulling from github should be handled so that the process continues, also it should be run in a different gevent greenlet.

**Comment by abom** [comment]
Even when pulling a repository directly:

```
➜  digitalmeX git:(development) git pull
ssh: connect to host github.com port 22: Connection timed out
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

It happens randomly, re-doing `git pull` worked later!

**Comment by abom** [comment]
Fixed after removing exit(1) (maybe trying to pull in case of time-out is now working).
Just need to make sure gevent monkey patching to subprocess is done with [jumpscaleX](https://github.com/threefoldtech/jumpscaleX), but still cannot decide that on my own now (so doing `git pull` won't block gedis).
