### ISSUE TITLE
svg file is not processed

### ISSUE THREAD

**Issue by nbabenko** [threefoldfoundation/lapis-wiki#23]
SVG images in the text are not loaded

Page example: 
https://wiki.tokens.grid.tf/#/why_buy_tft 
- Links to svg images are valid, but svg files are not loaded

**Comment by abom** [comment]
Blocked by #22.

**Comment by abom** [comment]
Fixed in https://github.com/threefoldtech/jumpscaleX/pull/638

Should be working now.
