### ISSUE TITLE
docsite.js load error

### ISSUE THREAD

**Issue by samaradel** [threefoldfoundation/lapis-wiki#24]
pages don't load as expected
ex [more info](https://staging-lua.threefold.io/more_info) page it looks like:
![image](https://user-images.githubusercontent.com/11662805/58464616-52ddde80-8136-11e9-906c-8d273cd01e06.png)

![image](https://user-images.githubusercontent.com/11662805/58464641-5e310a00-8136-11e9-88a4-cb5161067a44.png)

it should be:
![image](https://user-images.githubusercontent.com/11662805/58464912-da2b5200-8136-11e9-812f-22c311dff255.png)

**Comment by abom** [comment]
Should be resolved by https://github.com/threefoldtech/jumpscale_weblibs/commit/da38da1e082ff985282ac69603d7499b374b78a6 which changed the way elements are updated with content.

The old way didn't handle the case where some elements may contain both references (handlebars) and other text content or elements (children).
