### ISSUE TITLE
team building  page in wikis doesn't work

### ISSUE THREAD

**Issue by Dinaamagdy** [threefoldfoundation/lapis-wiki#26]
as shown in the following photo , wikis page doesn't work correctly 
![image](https://user-images.githubusercontent.com/24386802/59366498-af4a1c00-8d3a-11e9-8656-789c8b6270d8.png)

**Comment by abom** [comment]
https://github.com/threefoldtech/OpenPublish/commit/9627908b73d5ace659628a1f367bfbc809b9674a
