### ISSUE TITLE
Auto Deployment doesn't work

### ISSUE THREAD

**Issue by samaradel** [threefoldfoundation/lapis-wiki#33]
![photo_2019-06-27_11-14-46](https://user-images.githubusercontent.com/11662805/60255580-53ea6300-98d0-11e9-88b8-8362176a38d7.jpg)
![photo_2019-06-27_10-24-06](https://user-images.githubusercontent.com/11662805/60255581-5482f980-98d0-11e9-979b-187c12e6fb54.jpg)
![photo_2019-06-27_11-14-46](https://user-images.githubusercontent.com/11662805/60255974-fe628600-98d0-11e9-9a7a-b022712918b8.jpg)

**Comment by abom** [comment]
Some repos has code generation (lapis websites for example), we need to skip this changes (as openpublish tool mange this repo directories, or just add generated files to .gitignore).

**Comment by abom** [comment]
Not relevant now, new publishing system will be on production later.
