### ISSUE TITLE
Tables is not rendered after include

### ISSUE THREAD

**Issue by nbabenko** [threefoldfoundation/lapis-wiki#4]
1. Write a table in MD file for the wiki:
https://github.com/threefoldfoundation/info_foundation/blob/development/docs/presentations/presentations_toc.md
2. The document is included into another with include:
https://github.com/threefoldfoundation/info_foundation/blob/development/docs/presentations/README.md
3. After include table is not rendered properly:
https://wiki2.grid.tf/wiki/foundation#/presentations/readme

**Comment by arahmanhamdy** [comment]
After debugging the issue it seems that the table itself isn't standard,
The standard table syntax needs to have `|` at beginning of line and at the end, not only in between.

**Comment by nbabenko** [comment]
oh thank you!)
