### ISSUE TITLE
Add ability to change Wiki title in the left top corner

### ISSUE THREAD

**Issue by nbabenko** [threefoldfoundation/lapis-wiki#8]
<img width="253" alt="Screen Shot 2019-04-25 at 1 57 30 PM" src="https://user-images.githubusercontent.com/4426772/56731017-19463c00-6762-11e9-8d2f-b9a8112c9adb.png">

**Comment by abom** [comment]
Should be done via openpublish tool (jumpscalex/digitalmex).
